CREATE TABLE PELICULAS(
ID_PELI INT PRIMARY KEY,
NOMBRE VARCHAR2(90) NOT NULL,
PRECIO FLOAT NOT NULL,
FECHA_LANZ DATE NOT NULL, 
STOCK INT NOT NULL
);

CREATE SEQUENCE GENERA_ID_PELICULAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EJECUTA_SEC_PELICULAS
BEFORE INSERT 
ON PELICULAS
FOR EACH ROW 
BEGIN 
    SELECT GENERA_ID_PELICULAS.NEXTVAL INTO :NEW.ID_PELI FROM DUAL;
END;
